export const AUDIO_CONFIG = {
  SAMPLE_RATE: 24000,
  CHANNELS: 1,
  BIT_DEPTH: 16,
  MIN_BUFFER_SIZE: 48000,
  STOP_DELAY_MS: 200,
  MIC_REACTIVATION_DELAY_MS: 500,
} as const;

export const MICROPHONE_CONFIG = {
  SAMPLE_RATE_HERTZ: 24000,
  THRESHOLD: 0.8,
  SILENCE: '2.0',
} as const;

